### ISSUE TITLE
Проставить приоритеты работ для комплектации (карта ТО)

### ISSUE THREAD

**Issue by Aleksandr-87** [automagistre/www.automagistre.ru#304]
Комплексная диагностика -1 
Замена масла двигателя (Замена масла для обычных автомобилях) -2
Замена воздушного фильтра (Замена воздушного фильтра без каких либо разборов) -3  
Замена фильтра салона (Замена фильтра салона с легким доступом) -4 
Замена свечей зажигания (Замена свечей без дополнительного разбора) -5 
Замена тормозной жидкости (Стандартная работа по замене тормозной жидкости) -6 
Замена антифриза (Легкая замена антифриза) -7 
Замена масла раздаточной коробки -8
Замена масла заднего редуктора -9
Замена масла АКПП -10
Замена масла МКПП -10
Замена масла CVT -10
Замена жидкости сцепления (Замена жидкости сцепления) - 11
Замена масла ГУР-12

Снятие и установка защиты двигателя (Снятие и установка защиты двигателя 1 защита) - 21 
Компьютерная диагностика - 22 
Чистка дроссельной заслонки (Чистка БДЗ без дополнительных работа) - 23 
Чистка инжектора - 24

**Comment by KCH0000** [comment]
@grachevko 
Нужно запустить, чтобы проставить позиции в ТО
[work_positions.txt](https://github.com/automagistre/www.automagistre.ru/files/5608050/work_positions.txt)
